import { Router } from "express";
import multer from "multer";
import fs from "fs";
import { login } from "../controllers/authController";
import { getEmployees, getEmployeeById, createEmployee, updateEmployee, deleteEmployee } from "../controllers/employeeController";
import { getDepartments, createDepartment, updateDepartment, deleteDepartment } from "../controllers/departmentController";
import { getShifts, createShift, updateShift, deleteShift } from "../controllers/shiftController";
import { getDevices, createDevice, updateDevice, deleteDevice, testDeviceConnection, syncDevice } from "../controllers/deviceController";
import { getAttendanceLogs, getDailyAttendance, processDailyAttendance, mockSyncLogs } from "../controllers/attendanceController";
import { faceCheckIn } from "../controllers/faceController";
import { getAttendanceReport, exportAttendanceExcel, exportAttendancePdf } from "../controllers/reportController";
import { getDashboardSummary } from "../controllers/dashboardController";
import { getRoles, getPermissions, createRole, updateRole, deleteRole } from "../controllers/roleController";
import { authMiddleware } from "../middleware/auth";
import { requirePermission } from "../middleware/permission";

const uploadPath = process.env.UPLOAD_DIR || "public/uploads";
fs.mkdirSync(uploadPath, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: (_req, _file, cb) => cb(null, uploadPath), filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname}`) }) });
const router = Router();

router.post("/auth/login", login);
router.get("/dashboard/summary", authMiddleware, getDashboardSummary);
router.get("/employees", authMiddleware, requirePermission("EMPLOYEE_VIEW"), getEmployees);
router.get("/employees/:id", authMiddleware, requirePermission("EMPLOYEE_VIEW"), getEmployeeById);
router.post("/employees", authMiddleware, requirePermission("EMPLOYEE_CREATE"), upload.single("photo"), createEmployee);
router.put("/employees/:id", authMiddleware, requirePermission("EMPLOYEE_EDIT"), upload.single("photo"), updateEmployee);
router.delete("/employees/:id", authMiddleware, requirePermission("EMPLOYEE_DELETE"), deleteEmployee);
router.get("/departments", authMiddleware, requirePermission("DEPARTMENT_VIEW"), getDepartments);
router.post("/departments", authMiddleware, requirePermission("DEPARTMENT_CREATE"), createDepartment);
router.put("/departments/:id", authMiddleware, requirePermission("DEPARTMENT_EDIT"), updateDepartment);
router.delete("/departments/:id", authMiddleware, requirePermission("DEPARTMENT_DELETE"), deleteDepartment);
router.get("/shifts", authMiddleware, requirePermission("SHIFT_VIEW"), getShifts);
router.post("/shifts", authMiddleware, requirePermission("SHIFT_CREATE"), createShift);
router.put("/shifts/:id", authMiddleware, requirePermission("SHIFT_EDIT"), updateShift);
router.delete("/shifts/:id", authMiddleware, requirePermission("SHIFT_DELETE"), deleteShift);
router.get("/devices", authMiddleware, requirePermission("DEVICE_VIEW"), getDevices);
router.post("/devices", authMiddleware, requirePermission("DEVICE_CREATE"), createDevice);
router.put("/devices/:id", authMiddleware, requirePermission("DEVICE_EDIT"), updateDevice);
router.delete("/devices/:id", authMiddleware, requirePermission("DEVICE_DELETE"), deleteDevice);
router.post("/devices/:id/test-connection", authMiddleware, requirePermission("DEVICE_VIEW"), testDeviceConnection);
router.post("/devices/:id/sync", authMiddleware, requirePermission("DEVICE_SYNC"), syncDevice);
router.get("/attendance/logs", authMiddleware, getAttendanceLogs);
router.get("/attendance/daily", authMiddleware, getDailyAttendance);
router.post("/attendance/process", authMiddleware, processDailyAttendance);
router.post("/attendance/mock-sync", authMiddleware, mockSyncLogs);
router.post("/face/check-in", faceCheckIn);
router.get("/reports/attendance", authMiddleware, requirePermission("REPORT_VIEW"), getAttendanceReport);
router.get("/reports/attendance/excel", authMiddleware, requirePermission("REPORT_EXPORT"), exportAttendanceExcel);
router.get("/reports/attendance/pdf", authMiddleware, requirePermission("REPORT_EXPORT"), exportAttendancePdf);
router.get("/roles", authMiddleware, requirePermission("REPORT_VIEW"), getRoles);
router.get("/permissions", authMiddleware, requirePermission("REPORT_VIEW"), getPermissions);
router.post("/roles", authMiddleware, requirePermission("REPORT_EXPORT"), createRole);
router.put("/roles/:id", authMiddleware, requirePermission("REPORT_EXPORT"), updateRole);
router.delete("/roles/:id", authMiddleware, requirePermission("REPORT_EXPORT"), deleteRole);

export default router;
